// ── Scholarship Data ────────────────────────────────────────
var scholarships = [
    // Indigenous Students
    { id: "S1",  name: "Indspire Building Brighter Futures Bursaries",          cat: "Indigenous Students",                    desc: "Flexible funding options covering tuition, living expenses, and childcare for Indigenous students across Canada.",                                                     url: "https://indspire.ca/programs/students/bursaries-scholarships/" },
    { id: "S2",  name: "TD Scholarship for Indigenous Peoples",                  cat: "Indigenous Students",                    desc: "Valued up to $60,000 over four years, including tuition coverage and summer employment opportunities.",                                                              url: "https://www.td.com/ca/en/personal-banking/solutions/student-advice/indigenous-student-scholarships-grants-and-bursaries" },
    { id: "S3",  name: "Horatio Alger Indigenous Achievement Scholarship",       cat: "Indigenous Students",                    desc: "A $2,500 renewable award for Indigenous students demonstrating financial need and resilience.",                                                                       url: "https://horatioalger.ca/scholarships-and-services/scholarships/" },
    { id: "S4",  name: "Kathleen Blinkhorn Aboriginal Student Scholarship",      cat: "Indigenous Students",                    desc: "Specifically for Indigenous students living in non-profit housing within Ontario.",                                                                                 url: "https://onpha.on.ca/ONPHA/ONPHA/About/Kathleen_Blinkhorn_Aboriginal_Student_Scholarship.aspx" },
    { id: "S5",  name: "MNO Métis Student Bursary Program",                     cat: "Indigenous Students",                    desc: "Exclusively for verified citizens of the Métis Nation of Ontario attending participating institutions.",                                                             url: "https://www.metisnation.org/programs-and-services/education-training/post-secondary-education/" },
    { id: "S6",  name: "RBC Indigenous Student Awards Program",                  cat: "Indigenous Students",                    desc: "Provides $4,000 per academic year to assist with post-secondary education costs.",                                                                                  url: "https://www.rbc.com/indigenous/students.html" },
    { id: "S7",  name: "Husky Energy Indigenous Scholarship",                   cat: "Indigenous Students",                    desc: "Targeted toward Indigenous students pursuing degrees in business, engineering, or technology. Now administered by Cenovus.",                                           url: "https://www.cenovus.com/Careers/Students-and-new-graduates/Indigenous-Scholarship-Program" },
    { id: "S8",  name: "Canada Post Awards for Indigenous Students",             cat: "Indigenous Students",                    desc: "A $2,000 award designed for individuals returning to school after a period away from studies.",                                                                       url: "https://www.canadapost-postescanada.ca/cpc/en/our-company/giving-back-to-our-communities/canada-post-awards-for-indigenous-students.page" },
    { id: "S9",  name: "CN Diversity Scholarship",                               cat: "Indigenous Students",                    desc: "Targeted awards for Indigenous students focusing on transportation, engineering, or business fields.",                                                                url: "https://www.cn.ca/en/careers/internships-and-scholarships/diversity-scholarships/" },
    { id: "S10", name: "Nelson Scholarship for Indigenous Students",             cat: "Indigenous Students",                    desc: "Focuses on students demonstrating civic engagement, community leadership, and academic persistence.",                                                                 url: "https://www.nelson.com/scholarship/" },
    { id: "S11", name: "ATCO Indigenous Education Awards",                       cat: "Indigenous Students",                    desc: "Bursaries and scholarships for students originating from communities where ATCO operates.",                                                                           url: "https://www.atco.com/en-ca/our-commitment/indigenous-partnerships/indigenous-education-programs.html" },
    { id: "S12", name: "Chief Joe Mathias BC Aboriginal Scholarship",            cat: "Indigenous Students",                    desc: "A national-scope award supporting Indigenous leadership and post-secondary completion.",                                                                              url: "https://www.chiefjoemathias.ca/" },
    { id: "S13", name: "NWAC Helen Bassett Commemorative Student Award",         cat: "Indigenous Students",                    desc: "For Indigenous women and gender-diverse individuals pursuing legal, justice, or traditional studies.",                                                                url: "https://www.nwac.ca/scholarships-and-bursaries" },
    { id: "S14", name: "Inspire/Suncor Energy Indigenous Scholarship",          cat: "Indigenous Students",                    desc: "Tailored financial support for Indigenous youth enrolled in STEM or business faculties.",                                                                             url: "https://www.suncor.com/en-ca/sustainability/indigenous-relations/indigenous-student-program" },
    { id: "S15", name: "TC Energy Indigenous Legacy Scholarship",                cat: "Indigenous Students",                    desc: "Supports students working toward certificates, diplomas, or degrees in trades, STEM, or business.",                                                                  url: "https://www.tcenergy.com/community-giving/scholarships/" },
    { id: "S16", name: "Hatch Indigenous Scholarship",                           cat: "Indigenous Students",                    desc: "An $8,000 award dedicated to Indigenous engineering undergraduate students.",                                                                                       url: "https://www.hatch.com/en/Careers/Students-and-Graduates/Scholarships" },
    { id: "S17", name: "OPG Indigenous Student Awards",                          cat: "Indigenous Students",                    desc: "Administered by Ontario Power Generation to assist students pursuing energy-related fields.",                                                                         url: "https://www.opg.com/careers/student-awards/" },
    { id: "S18", name: "Bruce Power Indigenous Scholarship",                     cat: "Indigenous Students",                    desc: "Targeted regional funding for students residing in the Bruce, Grey, and Huron county areas.",                                                                        url: "https://www.brucepower.com/in-the-community/scholarships/" },
    { id: "S19", name: "Hydro One Indigenous Scholarship",                       cat: "Indigenous Students",                    desc: "Includes financial aid coupled with potential paid cooperative work terms at Hydro One.",                                                                            url: "https://www.hydroone.com/about/careers/students-and-new-graduates/scholarships" },
    { id: "S20", name: "Engineers Canada Indigenous Scholarship",                cat: "Indigenous Students",                    desc: "An undergraduate award highlighting leadership and excellence in engineering programs.",                                                                              url: "https://engineerscanada.ca/diversity/indigenous-peoples" },
    { id: "S21", name: "Indigenous Student Award (Renison University College)",  cat: "Indigenous Students",                    desc: "A $4,000 entrance or in-course award specifically for students registered at Renison/UWaterloo.",                                                                   url: "https://uwaterloo.ca/renison/indigenous-student-award" },
    { id: "S22", name: "WPIRG Campus Legacy Award for Indigenous Students",      cat: "Indigenous Students",                    desc: "A $3,000 award acknowledging community and social justice activism on campus.",                                                                                     url: "https://wpirg.org/" },
    { id: "S23", name: "The Gordon Foundation Indigenous Fellowships",           cat: "Indigenous Students",                    desc: "Geared toward graduate students conducting policy-focused research beneficial to Northern communities.",                                                               url: "https://gordonfoundation.ca/initiatives/jane-glassco-northern-fellowship/" },
    { id: "S24", name: "AFOA Canada Indigenous Scholarship",                     cat: "Indigenous Students",                    desc: "Aims to accelerate Indigenous representation in corporate finance, management, and governance.",                                                                      url: "https://afoa.ca/scholarships/" },
    { id: "S25", name: "CIBC Indigenous Student Awards",                         cat: "Indigenous Students",                    desc: "Financial assistance for students aspiring to build careers in the financial services sector.",                                                                     url: "https://www.cibc.com/en/about-cibc/careers/students-and-graduates/scholarships.html" },
    { id: "S26", name: "BMO Indigenous Scholarships",                            cat: "Indigenous Students",                    desc: "Open to full-time post-secondary students across diverse academic disciplines.",                                                                                    url: "https://jobs.bmo.com/ca/en/indigenous-students" },
    { id: "S27", name: "Scotiabank Indigenous Scholarship",                      cat: "Indigenous Students",                    desc: "Emphasizes supporting business, finance, and commerce undergraduate tracks.",                                                                                        url: "https://www.scotiabank.com/careers/en/careers/students-and-new-grads/scholarships.html" },
    { id: "S28", name: "Fasken Martineau DuMoulin Indigenous Scholarship",       cat: "Indigenous Students",                    desc: "Dedicated financial and mentorship support for Indigenous students enrolled in Canadian law schools.",                                                               url: "https://www.fasken.com/en/careers/students/diversity-and-inclusion" },
    { id: "S29", name: "Indspire Oil Sands Indigenous Scholarship",              cat: "Indigenous Students",                    desc: "Targeted technical, trade, and STEM funding supported by industrial sector partners.",                                                                               url: "https://indspire.ca/programs/students/bursaries-scholarships/" },
    { id: "S30", name: "The Belanger Indigenous Scholarship",                    cat: "Indigenous Students",                    desc: "A niche award acknowledging localized community leaders and cultural preservation efforts.",                                                                         url: "https://www.sac-isc.gc.ca/eng/1583774866495/1583774907675" },
    // Black Students
    { id: "S31", name: "BFCN Scholarship Directory Awards",                      cat: "Black Students",                         desc: "Multiple awards offered directly through the Black Foundation of Community Networks.",                                                                                url: "https://bfcn.ca/scholarships/" },
    { id: "S32", name: "RBC Pathways Diversity Award",                           cat: "Black Students",                         desc: "A $10,000 award for Black or Indigenous students pursuing careers in Capital Markets.",                                                                              url: "https://www.rbccm.com/en/careers/campus-recruiting/rbc-pathways-diversity-award-program.page" },
    { id: "S33", name: "BBPA National Scholarship Fund",                         cat: "Black Students",                         desc: "Administered by the Black Business and Professional Association across varied academic fields.",                                                                      url: "https://bbpa.org/the-scholarships/" },
    { id: "S34", name: "The I.D.E.A.L. Scholarship",                            cat: "Black Students",                         desc: "A $10,000 award centered on Black students displaying exceptional local community leadership.",                                                                     url: "https://www.ideal-scholarship.ca/" },
    { id: "S35", name: "U of T Engineering Entrance Scholarship for Black Students", cat: "Black Students",                    desc: "Faculty-specific entry-level funding acknowledging academic excellence and self-identification.",                                                                   url: "https://discover.engineering.utoronto.ca/money/scholarships/" },
    { id: "S36", name: "Winkelman Admission Scholarship",                        cat: "Black Students",                         desc: "University of Toronto award recognizing high-achieving applicants identifying as Black.",                                                                             url: "https://future.utoronto.ca/finances/scholarships/" },
    { id: "S37", name: "Alfie Pierce Admission Award",                           cat: "Black Students",                         desc: "Queen's University entrance accolade highlighting contributions to African/Caribbean communities.",                                                                  url: "https://www.queensu.ca/studentawards/admission-awards" },
    { id: "S38", name: "Kevin & Leigh Golding Family Bursary",                   cat: "Black Students",                         desc: "University of Guelph specific endowment targeting financial support for Black scholars.",                                                                           url: "https://www.uoguelph.ca/registrar/studentfinance/scholarships/index" },
    { id: "S39", name: "Waterloo Entrance Scholarships for Black Students",      cat: "Black Students",                         desc: "Substantial faculty awards ranging up to $40,000 for domestic applicants.",                                                                                          url: "https://uwaterloo.ca/future-students/financing/scholarships" },
    { id: "S40", name: "CIBC Black Student Scholarship",                         cat: "Black Students",                         desc: "Tailored to commercial and corporate banking tracks, pairing funding with internship potential.",                                                                    url: "https://www.cibc.com/en/about-cibc/careers/students-and-graduates/scholarships.html" },
    { id: "S41", name: "Deloitte Black Student Scholarship",                     cat: "Black Students",                         desc: "Supports undergraduate students navigating accounting, technology, and consulting programs.",                                                                         url: "https://www2.deloitte.com/ca/en/pages/careers/articles/students.html" },
    { id: "S42", name: "KPMG Black Student Scholarship",                         cat: "Black Students",                         desc: "Provides professional services alignment, funding, and structured mentorship.",                                                                                       url: "https://home.kpmg/ca/en/home/careers/students.html" },
    { id: "S43", name: "EY Black Student Scholarship",                           cat: "Black Students",                         desc: "Corresponds to students tracking toward professional CPA or corporate finance statuses.",                                                                             url: "https://www.ey.com/en_ca/careers/students" },
    { id: "S44", name: "PwC Black Student Scholarship",                          cat: "Black Students",                         desc: "A blend of academic funding and early-stage professional networking opportunities.",                                                                                 url: "https://www.pwc.com/ca/en/careers/campus.html" },
    { id: "S45", name: "Scotiabank Black Student Scholarship",                   cat: "Black Students",                         desc: "Aimed at breaking systemic barriers within tech, digital banking, and business infrastructure.",                                                                    url: "https://www.scotiabank.com/careers/en/careers/students-and-new-grads/scholarships.html" },
    { id: "S46", name: "BMO Black Student Scholarship",                          cat: "Black Students",                         desc: "Broad eligibility across undergraduate commerce, mathematics, and economics streams.",                                                                                url: "https://jobs.bmo.com/ca/en/students" },
    { id: "S47", name: "TD Black Student Scholarship",                           cat: "Black Students",                         desc: "Recognizes systemic barriers by offering tuition support and stable summer employment.",                                                                               url: "https://www.td.com/ca/en/about-td/for-investors/governance/diversity-and-inclusion" },
    { id: "S48", name: "Black Professionals in Tech Network (BPTN) Scholarships", cat: "Black Students",                       desc: "Geared directly toward engineering, math, and computer science program tracks.",                                                                                     url: "https://www.bptn.com/" },
    { id: "S49", name: "Canadian Association of Black Lawyers (CABL) Scholarships", cat: "Black Students",                     desc: "Niche funding supporting equity and representation within Canadian Juris Doctor (JD) programs.",                                                                      url: "https://cabl.ca/scholarships/" },
    { id: "S50", name: "Jamaican Canadian Association Scholarships",             cat: "Black Students",                         desc: "Recognizes outstanding academic and community volunteerism among youth of Caribbean heritage.",                                                                      url: "https://jcaontario.org/scholarship/" },
    { id: "S51", name: "Congress of Black Women of Canada Scholarships",         cat: "Black Students",                         desc: "Designed to uplift and financially support Black female students entering post-secondary tracks.",                                                                   url: "https://www.cbwc-ontario.com/" },
    { id: "S52", name: "ByBlacks.com Scholarship",                               cat: "Black Students",                         desc: "Niche award recognizing excellence in journalism, multimedia, and communications.",                                                                                   url: "https://byblacks.com/" },
    { id: "S53", name: "Onyx Initiative Scholarships",                           cat: "Black Students",                         desc: "Pairs career-readiness training, corporate recruitment access, and direct funding modules.",                                                                          url: "https://onyxinitiative.org/" },
    { id: "S54", name: "Black Health Alliance Scholarships",                     cat: "Black Students",                         desc: "Targeted toward health science, public policy, and community wellness study areas.",                                                                                 url: "https://blackhealthalliance.ca/" },
    { id: "S55", name: "Black Medical Students Association of Canada Awards",    cat: "Black Students",                         desc: "Specific systemic aid for Black medical students enrolled in accredited Canadian MD paths.",                                                                        url: "https://www.bmsac.ca/" },
    { id: "S56", name: "African Canadian Christian Network Scholarships",        cat: "Black Students",                         desc: "Provides structural support for youth highly involved in faith-based or local community groups.",                                                                   url: "https://accntoronto.com/scholarships/" },
    // Other Racialized & Ethnic Communities
    { id: "S57", name: "Jean Lumb Award",                                        cat: "Other Racialized & Ethnic Communities",  desc: "Honours Chinese-Canadian students achieving milestones in academics, athletics, or arts.",                                                                           url: "https://jeanlumbfoundation.ca/" },
    { id: "S58", name: "Cansbridge Fellowship",                                  cat: "Other Racialized & Ethnic Communities",  desc: "An accelerated international network fellowship often highlighting BIPOC innovators.",                                                                               url: "https://www.cansbridgefellowship.com/" },
    { id: "S59", name: "Villa Charities Undergraduate Student Scholarship",      cat: "Other Racialized & Ethnic Communities",  desc: "Dedicated to domestic undergraduate students of Italian-Canadian lineage.",                                                                                        url: "https://www.villacharities.com/" },
    { id: "S60", name: "Villa Charities Graduate Student Scholarship",           cat: "Other Racialized & Ethnic Communities",  desc: "A $5,000 scholarship assisting master's or doctoral students of Italian-Canadian heritage.",                                                                      url: "https://www.villacharities.com/" },
    { id: "S61", name: "National Congress of Italian-Canadians Scholarships",    cat: "Other Racialized & Ethnic Communities",  desc: "Provincial and regional chapters providing localized heritage-based bursaries.",                                                                                  url: "https://ncic.ca/" },
    { id: "S62", name: "Canadian Hispanic Bar Association Scholarship",          cat: "Other Racialized & Ethnic Communities",  desc: "Uplifts representation for Hispanic/Latinx legal minds attending Ontario law faculties.",                                                                          url: "https://www.canadianhispanicbar.com/" },
    { id: "S63", name: "Hispanic Canadian Heritage Council Awards",              cat: "Other Racialized & Ethnic Communities",  desc: "Community-driven niche funding recognizing Latinx youth demonstrating advocacy.",                                                                                  url: "https://hispaniccanadianheritage.ca/" },
    { id: "S64", name: "Afghan-Canadian Scholarship Fund",                       cat: "Other Racialized & Ethnic Communities",  desc: "Aims to reduce barriers for students of Afghan descent resettled or living in Canada.",                                                                            url: "https://afghancanadian.org/" },
    { id: "S65", name: "Somali Canadian Education & Rural Development Scholarships", cat: "Other Racialized & Ethnic Communities", desc: "Assists Somali-Canadian youth pursuing professional degrees and technical training.",                                                                       url: "https://www.sacda.ca/" },
    { id: "S66", name: "BIPOC Excellence / DIVERGENT Scholarship",              cat: "Other Racialized & Ethnic Communities",  desc: "University of Guelph specific initiative to expand campus-wide equity representation.",                                                                            url: "https://www.uoguelph.ca/registrar/studentfinance/scholarships/index" },
    { id: "S67", name: "A.L. Cochrane Scholarship",                             cat: "Other Racialized & Ethnic Communities",  desc: "U of T Victoria College entrance fund dedicated to self-identified BIPOC candidates.",                                                                            url: "https://vic.utoronto.ca/future-students/finances-and-awards/" },
    { id: "S68", name: "Malcolm X PACS Scholarship",                            cat: "Other Racialized & Ethnic Communities",  desc: "Conrad Grebel (UWaterloo) award recognizing peace and conflict studies focus in racialized youth.",                                                               url: "https://uwaterloo.ca/grebel/future-students/financial-aid-and-awards" },
    { id: "S69", name: "CN Diversity Scholarship (Visible Minorities)",         cat: "Other Racialized & Ethnic Communities",  desc: "Corporate allocation stream specific to visible minorities in tech or operations.",                                                                                url: "https://www.cn.ca/en/careers/internships-and-scholarships/diversity-scholarships/" },
    { id: "S70", name: "Fasken Diversity Scholarship",                          cat: "Other Racialized & Ethnic Communities",  desc: "Targeted law student support emphasizing second-year summer placement integration.",                                                                                url: "https://www.fasken.com/en/careers/students/diversity-and-inclusion" },
    // Students with Disabilities
    { id: "S71", name: "BMO Capital Markets Equity Through Education Scholarship", cat: "Students with Disabilities",           desc: "Administered via Lime Connect, backing global neurodivergent or disabled business talent.",                                                                          url: "https://www.limeconnect.com/programs/page/scholarships" },
    { id: "S72", name: "Canada Life + Lime Connect DevOps Award",               cat: "Students with Disabilities",             desc: "Technical scholarship track addressing students with disabilities navigating computer engineering.",                                                                  url: "https://www.limeconnect.com/programs/page/scholarships" },
    { id: "S73", name: "Johnson & Johnson Access-Ability Lime Scholarship",     cat: "Students with Disabilities",             desc: "Dedicated STEM and pharmaceutical industry alignment for disabled student tracks.",                                                                                  url: "https://www.limeconnect.com/programs/page/scholarships" },
    { id: "S74", name: "Microsoft Disability Scholarship",                      cat: "Students with Disabilities",             desc: "A $5,000 award empowering high school seniors with disabilities to venture into software tracks.",                                                                  url: "https://www.microsoft.com/en-us/diversity/programs/microsoftdisabilityscholarship.aspx" },
    { id: "S75", name: "Allegra Ford Thomas Scholarship",                       cat: "Students with Disabilities",             desc: "Tailored to students with documented learning disabilities transitioning to specialized colleges.",                                                                  url: "https://www.ncld.org/scholarships-and-awards/" },
    { id: "S76", name: "Anne Ford Scholarship",                                 cat: "Students with Disabilities",             desc: "A $10,000 multi-year commitment for students managing learning disabilities or ADHD.",                                                                               url: "https://www.ncld.org/scholarships-and-awards/" },
    { id: "S77", name: "Rick & Amanda Hansen Scholarship for Youth with Disabilities", cat: "Students with Disabilities",      desc: "Provides substantial coverage for youth with significant, visible physical functional limitations.",                                                                url: "https://www.rickhansen.com/our-work/school-program/scholarship" },
    { id: "S78", name: "NEADS National Student Awards",                         cat: "Students with Disabilities",             desc: "The National Educational Association of Disabled Students provides $3,000 cross-disability funding.",                                                                url: "https://www.neads.ca/en/about/projects/ete2/scholarship/" },
    { id: "S79", name: "Sarah Gaulin Memorial Scholarship",                     cat: "Students with Disabilities",             desc: "A unique national award prioritizing individuals dealing with diagnosed, chronic mental health conditions.",                                                          url: "https://gaulinfoundation.org/scholarships/" },
    { id: "S80", name: "CNIB Scholarships",                                     cat: "Students with Disabilities",             desc: "Provides structural support for blind or partially sighted youths starting university.",                                                                             url: "https://www.cnib.ca/en/programs-and-services/learn/scholarships-and-awards" },
    { id: "S81", name: "Alliance for Equality of Blind Canadians Scholarships", cat: "Students with Disabilities",             desc: "Peer-reviewed technical and academic bursaries for blind or deafblind students.",                                                                                    url: "https://www.blindcanadians.ca/programs/scholarship" },
    { id: "S82", name: "CHHA Scholarship Program",                              cat: "Students with Disabilities",             desc: "The Canadian Hard of Hearing Association supports deaf or hard of hearing post-secondary candidates.",                                                                url: "https://www.chha.ca/scholarships/" },
    { id: "S83", name: "Spina Bifida and Hydrocephalus Association of Canada Scholarships", cat: "Students with Disabilities", desc: "Highly localized and niche medical profile awards for impacted students.",                                                                                         url: "https://sbhac.ca/" },
    { id: "S84", name: "CF Canada Scholarships",                                cat: "Students with Disabilities",             desc: "Provides tailored educational funding modules for individuals living with Cystic Fibrosis.",                                                                         url: "https://www.cysticfibrosis.ca/" },
    { id: "S85", name: "Autism Ontario Scholarships",                           cat: "Students with Disabilities",             desc: "Includes specialized funds like the Eleanor Ritchie award for students on the autism spectrum.",                                                                    url: "https://www.autismontario.com/scholarships" },
    { id: "S86", name: "Learning Disabilities Association of Ontario (LDAO) Scholarships", cat: "Students with Disabilities",  desc: "Chapter-based bursary system addressing structural learning accommodations.",                                                                                       url: "https://www.ldao.ca/ldao-scholarships/" },
    { id: "S87", name: "Mattinson Scholarship Program for Students with Disabilities", cat: "Students with Disabilities",      desc: "Administered through Universities Canada to advance accessibility in higher tiers of education.",                                                                  url: "https://www.univcan.ca/programs-and-scholarships/" },
    { id: "S88", name: "Justin Eves Foundation Scholarships",                   cat: "Students with Disabilities",             desc: "Direct financial support helping Ontario students overcome learning disabilities via assistive tools.",                                                               url: "http://www.justinevesfoundation.com/" },
    { id: "S89", name: "Will Rogers Memorial Scholarship",                      cat: "Students with Disabilities",             desc: "Niche award favoring disabled applicants or those pursuing special education service certifications.",                                                               url: "https://www.willrogers.com/scholarship" },
    // LGBTQ2S+
    { id: "S90", name: "Bill 7 Award",                                          cat: "LGBTQ2S+ Students",                      desc: "A $5,000 award specific to 2SLGBTQI+ students demonstrating financial need in Ontario institutions.",                                                               url: "https://bill7award.ca/" },
    { id: "S91", name: "LOUD Foundation Scholarships",                          cat: "LGBTQ2S+ Students",                      desc: "National level awards supporting future community leaders and activists within the queer space.",                                                                    url: "https://loudbusiness.com/foundation/" },
    { id: "S92", name: "Start Proud Awards",                                    cat: "LGBTQ2S+ Students",                      desc: "Aimed at LGBTQ+ talent tracking toward professional services, banking, corporate law, or tech.",                                                                    url: "https://startproud.org/scholarships" },
    { id: "S93", name: "Imperial Sovereign Court of Toronto (ISCOT) Bursary",  cat: "LGBTQ2S+ Students",                      desc: "A highly localized grass-roots community bursary for queer or trans youth in the GTA/Ontario.",                                                                   url: "https://iscot.ca/" },
    { id: "S94", name: "The Pride Education Network Scholarship",               cat: "LGBTQ2S+ Students",                      desc: "Assists graduating secondary school students displaying leadership in diversity groups such as GSAs.",                                                              url: "https://pridenet.ca/" },
    { id: "S95", name: "Jeremy Dias Scholarship",                               cat: "LGBTQ2S+ Students",                      desc: "Maintained by the CCGSD to reward youth actively working to curb discrimination and transphobia.",                                                                 url: "https://ccgsd-ccdgs.org/scholarships/" },
    { id: "S96", name: "Lambda Foundation Scholarships",                        cat: "LGBTQ2S+ Students",                      desc: "University-endowed research grants and undergraduate assistance centered on queer/trans studies.",                                                                  url: "https://lambdafoundation.org/" },
    { id: "S97", name: "LGBTQ2+ STEM Scholarship",                             cat: "LGBTQ2S+ Students",                      desc: "Niche funding prioritizing marginalized queer individuals entering hard science domains.",                                                                          url: "https://startproud.org/scholarships" },
    { id: "S98", name: "Out On Bay Street Scholarships",                        cat: "LGBTQ2S+ Students",                      desc: "Historical corporate recruitment and support modules, structurally linked to Start Proud platforms.",                                                               url: "https://startproud.org/" },
    { id: "S99", name: "PFLAG Canada Scholarships",                             cat: "LGBTQ2S+ Students",                      desc: "Rewards youth allies and LGBTQ+ individuals who build community inclusion frameworks.",                                                                            url: "https://pflagcanada.ca/" },
    // Gender Equity & Women in STEM
    { id: "S100", name: "Opterus Helen Rose STEM Award",                        cat: "Gender Equity & Women in STEM",          desc: "A $5,000 scholarship celebrating entrepreneurial women pursuing science, math, or technology.",                                                                     url: "https://opterus.com/scholarships" },
    { id: "S101", name: "Opterus Valerie Ann Arts Award",                       cat: "Gender Equity & Women in STEM",          desc: "A $5,000 scholarship tailored toward young women expanding boundaries in creative or fine arts.",                                                                 url: "https://opterus.com/scholarships" },
    { id: "S102", name: "L'Oreal Canada For Women in Science",                  cat: "Gender Equity & Women in STEM",          desc: "Prestigious postgraduate fellowships supporting elite female research initiatives.",                                                                                url: "https://www.forwomeninscience.com/" },
    { id: "S103", name: "Engineers Canada Women in Engineering Scholarship",    cat: "Gender Equity & Women in STEM",          desc: "Designed to boost systemic female representation across accredited engineering modules.",                                                                           url: "https://engineerscanada.ca/awards-and-honours/scholarships" },
    { id: "S104", name: "CEMF Women in Engineering Awards",                     cat: "Gender Equity & Women in STEM",          desc: "Canadian Engineering Memorial Foundation funding prioritizing leadership over pure academic GPA.",                                                                  url: "https://www.cemf.ca/" },
    { id: "S105", name: "Palantir Women in Technology Scholarship",             cat: "Gender Equity & Women in STEM",          desc: "A global tech scholarship supporting female-identifying computer science undergraduates.",                                                                          url: "https://www.palantir.com/students/scholarship/wit/" },
    { id: "S106", name: "Women in Capital Markets (WCM) Scholarships",          cat: "Gender Equity & Women in STEM",          desc: "A financial aid initiative seeking to accelerate gender parity on trading floors and investment suites.",                                                          url: "https://wcm.ca/programs" },
    { id: "S107", name: "Women in Aviation International Scholarships",         cat: "Gender Equity & Women in STEM",          desc: "Highly specialized aviation, piloting, and aerospace engineering bursaries open to Canadian applicants.",                                                          url: "https://www.wai.org/scholarships" }
];

// ── Category accent colours ─────────────────────────────────
var catAccent = {
    "Indigenous Students":                   "#c8832a",
    "Black Students":                        "#2e7d32",
    "Other Racialized & Ethnic Communities": "#3f51b5",
    "Students with Disabilities":            "#7b1fa2",
    "LGBTQ2S+ Students":                     "#c2185b",
    "Gender Equity & Women in STEM":         "#0090a1"
};

var catBg = {
    "Indigenous Students":                   "#fdf3e7",
    "Black Students":                        "#edf7ed",
    "Other Racialized & Ethnic Communities": "#eef0fb",
    "Students with Disabilities":            "#f6eefb",
    "LGBTQ2S+ Students":                     "#fde9f0",
    "Gender Equity & Women in STEM":         "#e6f7f9"
};

// ── Build cards into .RightBox ──────────────────────────────
var rightBox = document.getElementById('scholarshipRightBox');

scholarships.forEach(function(s) {
    var accent = catAccent[s.cat] || '#c8992a';
    var bg     = catBg[s.cat]     || '#f9f6f0';

    var card = document.createElement('div');
    card.id        = s.id;
    card.className = 'ScholarshipsCard';
    card.setAttribute('tabindex', '0');
    card.setAttribute('role', 'button');
    card.setAttribute('aria-label', 'View details for ' + s.name);

    // Apply per-category colours directly on the card
    card.style.borderTopColor  = accent;
    card.style.backgroundColor = bg;

    card.innerHTML =
        '<span style="display:block;font-size:0.65rem;font-weight:700;letter-spacing:0.07em;text-transform:uppercase;color:' + accent + ';margin-bottom:0.4rem;">' + escHtml(s.cat) + '</span>' +
        '<h3 style="font-family:\'Playfair Display\',Georgia,serif;font-size:0.92rem;font-weight:600;line-height:1.3;color:#0d2340;flex:1;">' + escHtml(s.name) + '</h3>';

    card.addEventListener('click', function() { openModal(s); });
    card.addEventListener('keydown', function(e) {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openModal(s); }
    });

    rightBox.appendChild(card);
});

// ── Modal elements ──────────────────────────────────────────
var overlay  = document.getElementById('scModal');
var mCat     = document.getElementById('scModalCat');
var mTitle   = document.getElementById('scModalTitle');
var mDesc    = document.getElementById('scModalDesc');
var mLink    = document.getElementById('scModalLink');
var mClose   = document.getElementById('scModalClose');

function openModal(s) {
    var accent = catAccent[s.cat] || '#c8992a';
    mCat.textContent   = s.cat;
    mCat.style.color   = accent;
    mTitle.textContent = s.name;
    mDesc.textContent  = s.desc;
    mLink.href         = s.url;
    mLink.style.background = accent;
    overlay.classList.add('sc-open');
    document.body.style.overflow = 'hidden';
    mClose.focus();
}

function closeModal() {
    overlay.classList.remove('sc-open');
    document.body.style.overflow = '';
}

mClose.addEventListener('click', closeModal);
overlay.addEventListener('click', function(e) { if (e.target === overlay) closeModal(); });
document.addEventListener('keydown', function(e) { if (e.key === 'Escape') closeModal(); });

// ── Utility ─────────────────────────────────────────────────
function escHtml(str) {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}